name: Add/Modify SPDX Tool
description: Add or Modify an Open Source Tool on the spdx.dev/tools website
title: "[Open Source Tool Request]: "
labels: ["tools"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in the information below to request a new open source tool to be added to the SPDX website or a modification to an existing tool
  - type: dropdown
    id: type
    attributes:
      label: Open Source or Commercial
      description: Is this an open source or a commercial tool?
    - options:
      - open source
      - commercial
    - default: 0
    validations:
      required: true
- type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true